[package]
name = "core_game"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
anyhow = "1.0"
log = "0.4"

[dev-dependencies]
env_logger = "0.9"
